# Generated by Django 4.2.6 on 2023-10-16 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project2', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='storeItems',
            new_name='storeItem',
        ),
    ]
