# Generated by Django 4.2.6 on 2023-10-16 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project2', '0003_alter_storeitem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
