# Generated by Django 4.2.6 on 2023-10-16 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project2', '0005_alter_storeitem_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeitem',
            name='image',
        ),
    ]
