# Generated by Django 4.2.6 on 2023-10-16 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project2', '0006_remove_storeitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeitem',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
