# Generated by Django 4.2.6 on 2023-10-17 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project2', '0010_alter_storeitem_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storeitem',
            old_name='id',
            new_name='title',
        ),
    ]
